---
dist: xenial
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos6-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos6-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1404-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1404-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=debian8-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian8-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "afO7v8HsmULSTuhn7QtSdm8C+N94sQK4MCx2eIptnjq5GH8AkajgIeo2Nv1DOP17oXBoCDwTOt6FEWEKD1P80WSA10Wa6OBKhlaoQmqKjFpSi+WNIPXLFekdXCJL5R6eLnglYHozTuIzEqB3ycxgphbim8+9fpbK4Uto3gNVDV0zVBLuyk9Se0xV9kSBwcQWpfvofx5/TOZOrxo/lDb3SbYPgqtjJYaEI91SmMom9kO9bzEn2gM2WUya+6vL4UxuzZmdlB5d8O6o1O5Vq1s2dJqoz7sY4CnMaRHhV01FQiqGtPwJ53bYYu2cAhXajL2ROPYLQTt+up32ZnCNL2zWQ4+OwTb7I/vR2uPEROTnP9eLEU2EaMXV0ajY1pP0SnD/zMMkEmcsAKRPX+yD8IsvlXri+dIJY+ftvSxhm328xGTb7Oz4MgU6m0qTgo9RMPHp59hTu4QaoKMTEmHwSFoZ/ilk47+qyNrk20wT6PAYDm28/3+9jz6YQefc1RjbNjnD7szuU0LozUVWpucjhEXGlYT58BjwIPPYu4qHehQJkS9B6/U9AIenef7Hledqh9lng918Fao3rDhUs672PmchzgN7Cwiem8ngkvtSG4SJSaATEMKiecaI1ABs0SQYoAmCapTn/eWRTbSIYNFpvfyAWG0kipAGBOtsJtmrysSFfy8="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
